external_components:
  - source: github://gregb79/esphome-pr6300@main
    components: [cc1101, iris]

remote_transmitter:
  id: tx
  pin: GPIO32
  carrier_duty_percent: 100%

globals:
  - id: iris
    type: remote_transmitter::IrisProtocol*

init:
  - lambda: |-
      auto iris_proto = new remote_transmitter::IrisProtocol();
      iris_proto->set_parent(id(tx));
      id(iris) = iris_proto;

button:
  - platform: template
    name: "Default Iris"
    on_press:
      - remote_transmitter.transmit_iris:   # uses defaults

  - platform: template
    name: "Blue Pool"
    on_press:
      - remote_transmitter.transmit_iris:
          instruction: Blue      # VS Code will autocomplete
          mode: pool             # autocomplete available

  - platform: template
    name: "Red Spa"
    on_press:
      - remote_transmitter.transmit_iris:
          instruction: Red
          mode: spa
